name: Python package

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
        # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
        contents: write

    steps:
      - uses: actions/checkout@v4
        with:
            ref: ${{ github.head_ref }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install package (with dev dependencies)
        run: |
          pip install --upgrade pip
          pip install -e .[dev]

      - name: Test with pytest and generate badges (coverage/tests)
        run: |
          pytest \
          --junitxml=reports/junit/junit.xml \
          --html=reports/junit/report.html \
          --cov=mlballistics \
          tests/

          coverage report
          coverage xml
          coverage html

          mkdir reports/coverage
          mv coverage.xml reports/coverage/coverage.xml
          mv htmlcov reports/coverage/htmlcov
          rm reports/coverage/htmlcov/.gitignore

          pip install flake8 flake8-html
          flake8 src \
              --exit-zero \
              --statistics \
              --format=html \
              --htmldir ./reports/flake8 \
              --tee \
              --output-file flake8stats.txt

          pip install genbadge[all]
          genbadge coverage
          genbadge tests
          genbadge flake8 -i - < flake8stats.txt

          mv flake8stats.txt reports/flake8/


          if [ ! -d "badges" ]; then
              mkdir badges
          fi

          mv coverage-badge.svg badges/
          echo "coverage-badge.svg moved to badges"
          mv tests-badge.svg badges/
          echo "tests-badge.svg moved to badges"
          mv flake8-badge.svg badges/
          echo "flake8-badge.svg moved to badges"


          if [ -d "badges/reports" ]; then
              rm -r badges/reports
          fi

          mv reports badges/reports
          echo "reports folder moved to badges"

      - name: push badges to repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: "[skip ci] add badges"
            file_pattern: 'badges/*.svg'


      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV


      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@v2

      - run: mkdocs gh-deploy --force

      - name: push reports to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./badges/reports
          publish_branch: gh-pages
          destination_dir: reports/

