name: Python package

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      
      - name: Install package (with dev dependencies)
        run: |
          pip install --upgrade pip
          pip install -e .[dev]

      - name: Test with pytest
        run: |
          pytest tests/