name: Python package

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest]
        python-version: ["3.11"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      
      - name: Install package (with dev dependencies)
        run: |
          pip install --upgrade pip
          pip install -e .[dev]

      - name: Test with pytest and generate badges (coverage/tests)
        run: |
            pytest \
                --junitxml=reports/junit/junit.xml \
                --html=reports/junit/report.html \
                --cov=mlballistics \
                tests/
        
            coverage report
            coverage xml
            coverage html
        
            mkdir reports/coverage
            mv coverage.xml reports/coverage/coverage.xml
            mv htmlcov reports/coverage/htmlcov

            pip install genbadge[all]
            genbadge coverage
            genbadge tests
            
            if [ ! -d "badges" ]; then
                mkdir badges
            fi
            mv coverage-badge.svg badges/
            echo "coverage-badge.svg moved to badges folder"
            mv tests-badge.svg badges/
            echo "tests-badge.svg moved to badges folder"
            
            rm -r reports/
        
      - name: push badges to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: "[skip ci] add badges"
            commit_options: '--no-verify'
            file_pattern: badges/*.svg
            repository: ${{ github.repository }}
            branch: ${{ github.ref }}


